apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: developed-falcon-nodejs 
  janus-idp.io/tekton: developed-falcon-nodejs
  backstage.io/kubernetes-id: developed-falcon-nodejs
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: developed-falcon-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  